### ISSUE TITLE
[Android] Package io.stewan.capacitor.fcm.FCMPlugin does not exist

### ISSUE THREAD

**Issue by chvonrohr** [capacitor-community/fcm#44]
I started a new issue with the same title I found an existing issue ;)
But steps mentioned did not help. I also tried `./gradlew --refresh-dependencies` and amending `capacitor.settings.gradle` as in #43 - but did not help.

**Any ideas, what I could do to force copying plugin files and install all needed dependencies?**

![image](https://user-images.githubusercontent.com/1733057/85986605-d4b0d300-b9ec-11ea-9129-5561362f6bbc.png)

**To Reproduce**
Steps according to Android Setup: https://github.com/capacitor-community/fcm
Using gradle 6.1

**Expected behavior**
Should find import of `io.stewan.capacitor.fcm.FCMPlugin`.
I also tried to copy java files manually to the `src/` folder, but then Firebase Classes can't be found.

**Screenshots**
Where should the java package be placed? 
![image](https://user-images.githubusercontent.com/1733057/85989333-aaf9ab00-b9f0-11ea-99c6-3d5f948e7715.png)

**Additional context**
Gradle 6.1
Andriod Studio 4.0

**Comment by stewwan** [comment]
fixed in 1.0.5
please check out the android breaking change on [changelog](https://github.com/capacitor-community/fcm/blob/master/CHANGELOG.md#breaking-change)

**Comment by chvonrohr** [comment]
YOU ARE MARVELOUS! Thank you.

It works, except one thing:
The imports `import com.google.firebase.iid.FirebaseInstanceId;` and `import com.google.firebase.messaging.FirebaseMessaging;` could not be found in `FCMPlugin.java`. It's listed under "External Libraries", but still not found.

I added `implementation 'com.google.firebase:firebase-messaging:20.2.1'` to my `build.gradle` what did it so far. But I guess there is still something wrong (maybe only in my setup).

**Comment by stewwan** [comment]
That’s weird @chvonrohr , did you run `npx cap sync android` after npm install?

**Comment by chvonrohr** [comment]
my fault, sorry @stewwan 
For any reason, I had also capacitor-fcm installed. After removing this and clean build, all was good agin.
