### ISSUE TITLE
Firebase InstanceID has been removed - iOS builds failing

### ISSUE THREAD

**Issue by denisLoncaric** [capacitor-community/fcm#67]
**Describe the bug**
We are using `fastlane` to build iOS apps. Since 11th of May 2021 our builds are failing with error message:

`@capacitor-community/fcm/ios/Plugin/Plugin/Plugin.swift:7:8: [31mno such module 'FirebaseInstanceID'

import FirebaseInstanceID`

The [Firebase iOS SDK (v8.0.0)](https://firebase.google.com/support/release-notes/ios?hl=de#8.0.0) is now available and Firebase InstanceID has been removed.

There is a migration [guide](https://firebase.google.com/docs/projects/manage-installations#fid-iid) on how to move from Instance ID to Firebase Installations.

**Expected behavior**
After migration there should be no issues with this plugin.

**Comment by damienromito** [comment]
I have the same probleme

![Capture d’écran 2021-05-12 à 19 48 13](https://user-images.githubusercontent.com/603808/118021152-348d3f80-b35b-11eb-841a-72a24d8b22fa.png)

**Comment by puopg** [comment]
Bump, yup im hitting the same thing. Can someone mention what changed please?

**Comment by chvonrohr** [comment]
We fixed the version for firebase in the podfile so its working meanwhile

**Comment by puopg** [comment]
Awesome, same here, that ended up working:
 
For those who may care:
```
target 'App' do
  capacitor_pods
  # Add your Pods here
  pod 'FirebaseCore', '~> 7.9.0'
  pod 'Firebase/Messaging', '~> 7.9.0'
end
```

**Comment by typeoneerror** [comment]
Should probably update https://github.com/capacitor-community/fcm/blob/master/ios/Plugin/Podfile#L9-L10 to @puopg's change above. 

Can submit a PR if it helps!

**Comment by chvonrohr** [comment]
Same problem for Android here. App crashes when trying to register Push Notification
```
caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;
        at com.getcapacitor.plugin.PushNotifications.register(PushNotifications.java:83)
java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceId" on path:
```

I assume this is the same problem but for Android. Any recommendations how to fix that (e.g. define version in `build.gradle`)?

**Comment by iOlivier** [comment]
I also found a solution without having to change the plugin package.

You can go to `ios/App/Podfile` and add the desired FirebaseCore version like this underneath the existing pods:
```
def capacitor_pods
  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
  pod 'CapacitorCommunityFcm', :path => '../../node_modules/@capacitor-community/fcm'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
  # Do not delete

  pod 'FirebaseCore', '~> 7.11.0'
end
```
After you did the change, don't forget to run `pod update`.

**Comment by Dave-Nandwa** [comment]
@iOlivier and what Firebase Messaging > > version did you input as well? Still `7.11.0`?

**Comment by stewones** [comment]
@denisLoncaric can you check if this remains an issue on latest plugin version (v1.1.2) ?
Thank you

**Comment by magiclockers** [comment]
@stewones  issue still occur in v1.1.2, just tested

**Comment by stewones** [comment]
fixed on v2, please have a try @magiclockers

**Comment by nkCreation** [comment]
and for capacitor 2 users ?

**Comment by stewones** [comment]
For those having issues with cap v2, try adding this in your app podfile

```
target 'App' do
  capacitor_pods
  # Add your Pods here
  pod 'Firebase/Messaging', '~> 7.11.0'
end
```

**Comment by BenjaminDish** [comment]
I'm still experiencing this error with Capacitor v2, this plugin v1.1.2 and 

```
target 'App' do
  capacitor_pods
  # Add your Pods here
  pod 'FirebaseCore', '~> 7.11.0'
  pod 'Firebase/Messaging', '~> 7.11.0'
end
```

Did I miss something ?
